from __future__ import annotations

from typing import Any, Optional
from fastapi import APIRouter, Query

router = APIRouter(prefix="/api/themes", tags=["themes"])


THEMES_CATALOG: list[dict[str, Any]] = [
    # ==================== 1. BASIC & MINIMAL (10) ====================
    {
        "id": "minimal-clean",
        "name": "Minimalist Oq",
        "category": "basic",
        "tags": ["oddiy", "minimal", "oq", "clean", "white", "biznes", "shaxsiy"],
        "backgroundType": "solid",
        "background": "#f8fafc",
        "surface": "#ffffff",
        "text": "#0f172a",
        "accent": "#0f766e",
        "radius": 12,
        "blur": 0,
        "overlayOpacity": 0,
        "overlayColor": "#000000",
        "buttonStyle": "solid",
    },
    {
        "id": "dark-stealth",
        "name": "Dark Stealth",
        "category": "basic",
        "tags": ["oddiy", "qora", "dark", "stealth", "it", "developer", "dasturchi"],
        "backgroundType": "solid",
        "background": "#09090b",
        "surface": "#18181b",
        "text": "#fafafa",
        "accent": "#38bdf8",
        "radius": 12,
        "blur": 0,
        "overlayOpacity": 0,
        "overlayColor": "#000000",
        "buttonStyle": "solid",
    },
    {
        "id": "nordic-slate",
        "name": "Nordic Slate",
        "category": "basic",
        "tags": ["oddiy", "kulrang", "nordic", "slate", "cool", "sovuq"],
        "backgroundType": "solid",
        "background": "#0f172a",
        "surface": "#1e293b",
        "text": "#f1f5f9",
        "accent": "#06b6d4",
        "radius": 14,
        "blur": 0,
        "overlayOpacity": 0,
        "overlayColor": "#000000",
        "buttonStyle": "solid",
    },
    {
        "id": "warm-sand",
        "name": "Issiq Qum (Warm Sand)",
        "category": "basic",
        "tags": ["oddiy", "qum", "issiq", "warm", "sand", "creamy", "qahva"],
        "backgroundType": "solid",
        "background": "#fdfbf7",
        "surface": "#f5efe6",
        "text": "#443525",
        "accent": "#b45309",
        "radius": 14,
        "blur": 0,
        "overlayOpacity": 0,
        "overlayColor": "#000000",
        "buttonStyle": "solid",
    },
    {
        "id": "pure-contrast",
        "name": "Pure Contrast (B&W)",
        "category": "basic",
        "tags": ["oddiy", "oq qora", "contrast", "black white", "monochrome"],
        "backgroundType": "solid",
        "background": "#000000",
        "surface": "#111111",
        "text": "#ffffff",
        "accent": "#ffffff",
        "radius": 8,
        "blur": 0,
        "overlayOpacity": 0,
        "overlayColor": "#000000",
        "buttonStyle": "solid",
    },
    {
        "id": "sage-tranquil",
        "name": "Adaçayı (Sage Green)",
        "category": "basic",
        "tags": ["oddiy", "yashil", "sage", "green", "tabiiy", "tinch", "organic"],
        "backgroundType": "solid",
        "background": "#f2f7f4",
        "surface": "#e2ece6",
        "text": "#1c3327",
        "accent": "#15803d",
        "radius": 16,
        "blur": 0,
        "overlayOpacity": 0,
        "overlayColor": "#000000",
        "buttonStyle": "solid",
    },
    {
        "id": "pink-velvet",
        "name": "Pushti Velvet (Soft Velvet)",
        "category": "basic",
        "tags": ["oddiy", "pushti", "pink", "velvet", "ayollar", "gozallik"],
        "backgroundType": "solid",
        "background": "#fff1f2",
        "surface": "#ffe4e6",
        "text": "#881337",
        "accent": "#e11d48",
        "radius": 16,
        "blur": 0,
        "overlayOpacity": 0,
        "overlayColor": "#000000",
        "buttonStyle": "solid",
    },
    {
        "id": "deep-indigo",
        "name": "Deep Indigo",
        "category": "basic",
        "tags": ["oddiy", "indigo", "ko'k", "binafsha", "deep", "to'q"],
        "backgroundType": "solid",
        "background": "#1e1b4b",
        "surface": "#312e81",
        "text": "#e0e7ff",
        "accent": "#818cf8",
        "radius": 14,
        "blur": 0,
        "overlayOpacity": 0,
        "overlayColor": "#000000",
        "buttonStyle": "solid",
    },
    {
        "id": "charcoal-matte",
        "name": "Charcoal Matte",
        "category": "basic",
        "tags": ["oddiy", "charcoal", "matte", "qora", "kulrang", "premium"],
        "backgroundType": "solid",
        "background": "#18181b",
        "surface": "#27272a",
        "text": "#f4f4f5",
        "accent": "#a1a1aa",
        "radius": 10,
        "blur": 0,
        "overlayOpacity": 0,
        "overlayColor": "#000000",
        "buttonStyle": "solid",
    },
    {
        "id": "lavender-mist",
        "name": "Lavanda Tumani",
        "category": "basic",
        "tags": ["oddiy", "lavanda", "binafsha", "lavender", "mist", "xushbo'y"],
        "backgroundType": "solid",
        "background": "#f5f3ff",
        "surface": "#ede9fe",
        "text": "#3b0764",
        "accent": "#7c3aed",
        "radius": 16,
        "blur": 0,
        "overlayOpacity": 0,
        "overlayColor": "#000000",
        "buttonStyle": "solid",
    },

    # ==================== 2. MODERN GRADIENT (12) ====================
    {
        "id": "neon-violet",
        "name": "Neon Violet & Indigo",
        "category": "gradient",
        "tags": ["gradient", "neon", "violet", "binafsha", "yangi", "zamonaviy", "it"],
        "backgroundType": "gradient",
        "gradient": "linear-gradient(135deg, #0f172a 0%, #312e81 50%, #4c1d95 100%)",
        "surface": "rgba(255, 255, 255, 0.08)",
        "text": "#ffffff",
        "accent": "#a855f7",
        "radius": 16,
        "blur": 16,
        "overlayOpacity": 0.15,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "sunset-glow",
        "name": "Quyosh Botishi (Sunset Glow)",
        "category": "gradient",
        "tags": ["gradient", "quyosh", "botish", "sunset", "orange", "qizil", "yoz"],
        "backgroundType": "gradient",
        "gradient": "linear-gradient(135deg, #431407 0%, #9a3412 50%, #ea580c 100%)",
        "surface": "rgba(255, 255, 255, 0.12)",
        "text": "#ffffff",
        "accent": "#f97316",
        "radius": 16,
        "blur": 16,
        "overlayOpacity": 0.15,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "emerald-mint",
        "name": "Zumrad & Yalpiz (Emerald)",
        "category": "gradient",
        "tags": ["gradient", "zumrad", "yalpiz", "emerald", "mint", "moliya", "pul", "tibbiyot"],
        "backgroundType": "gradient",
        "gradient": "linear-gradient(135deg, #022c22 0%, #065f46 50%, #059669 100%)",
        "surface": "rgba(255, 255, 255, 0.1)",
        "text": "#ffffff",
        "accent": "#10b981",
        "radius": 14,
        "blur": 16,
        "overlayOpacity": 0.15,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "cyber-cyan",
        "name": "Cyberpunk Cyan & Blue",
        "category": "gradient",
        "tags": ["gradient", "cyberpunk", "cyan", "ko'k", "neon", "texnologiya", "dasturlash"],
        "backgroundType": "gradient",
        "gradient": "linear-gradient(135deg, #050b14 0%, #0c2340 50%, #0891b2 100%)",
        "surface": "rgba(255, 255, 255, 0.08)",
        "text": "#f0fdfa",
        "accent": "#06b6d4",
        "radius": 16,
        "blur": 16,
        "overlayOpacity": 0.15,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "cherry-blush-grad",
        "name": "Gilos Sharf (Cherry Blush)",
        "category": "gradient",
        "tags": ["gradient", "gilos", "pushti", "cherry", "blush", "moda", "fashion", "gozallik"],
        "backgroundType": "gradient",
        "gradient": "linear-gradient(135deg, #4c0519 0%, #881337 50%, #e11d48 100%)",
        "surface": "rgba(255, 255, 255, 0.1)",
        "text": "#ffffff",
        "accent": "#fb7185",
        "radius": 16,
        "blur": 16,
        "overlayOpacity": 0.15,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "aurora-borealis",
        "name": "Shimol Yog'dusi (Aurora)",
        "category": "gradient",
        "tags": ["gradient", "aurora", "shimol", "yashil", "binafsha", "sehrli", "tun"],
        "backgroundType": "gradient",
        "gradient": "linear-gradient(135deg, #09131b 0%, #0f3d3e 50%, #1e1b4b 100%)",
        "surface": "rgba(255, 255, 255, 0.1)",
        "text": "#ffffff",
        "accent": "#2dd4bf",
        "radius": 16,
        "blur": 16,
        "overlayOpacity": 0.2,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "golden-luxury-grad",
        "name": "Oltin Elita (Golden Luxury)",
        "category": "gradient",
        "tags": ["gradient", "oltin", "gold", "luxury", "qimmatbaho", "vip", "premium"],
        "backgroundType": "gradient",
        "gradient": "linear-gradient(135deg, #1c1917 0%, #292524 50%, #44403c 100%)",
        "surface": "rgba(245, 158, 11, 0.08)",
        "text": "#fef3c7",
        "accent": "#f59e0b",
        "radius": 12,
        "blur": 16,
        "overlayOpacity": 0.15,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "ocean-deep",
        "name": "Okean Tubi (Deep Ocean)",
        "category": "gradient",
        "tags": ["gradient", "okean", "suv", "ocean", "dengiz", "deep", "moviy"],
        "backgroundType": "gradient",
        "gradient": "linear-gradient(135deg, #030712 0%, #082f49 50%, #0369a1 100%)",
        "surface": "rgba(255, 255, 255, 0.08)",
        "text": "#f0f9ff",
        "accent": "#38bdf8",
        "radius": 16,
        "blur": 16,
        "overlayOpacity": 0.2,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "candy-pop",
        "name": "Candy Pop & Peach",
        "category": "gradient",
        "tags": ["gradient", "candy", "shirinlik", "shaftoli", "peach", "yorqin", "yoshlar"],
        "backgroundType": "gradient",
        "gradient": "linear-gradient(135deg, #f43f5e 0%, #fb923c 50%, #facc15 100%)",
        "surface": "rgba(255, 255, 255, 0.25)",
        "text": "#ffffff",
        "accent": "#ffffff",
        "radius": 18,
        "blur": 14,
        "overlayOpacity": 0.1,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "mystic-plum",
        "name": "Sehrli Olxo'ri (Mystic Plum)",
        "category": "gradient",
        "tags": ["gradient", "olxori", "plum", "mystic", "binafsha", "tungi"],
        "backgroundType": "gradient",
        "gradient": "linear-gradient(135deg, #2e1065 0%, #581c87 50%, #831843 100%)",
        "surface": "rgba(255, 255, 255, 0.1)",
        "text": "#faf5ff",
        "accent": "#c084fc",
        "radius": 16,
        "blur": 16,
        "overlayOpacity": 0.15,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "fire-ember",
        "name": "Olovli Cho'g' (Fire Ember)",
        "category": "gradient",
        "tags": ["gradient", "olov", "chog", "fire", "ember", "sport", "fitness", "energiya"],
        "backgroundType": "gradient",
        "gradient": "linear-gradient(135deg, #180505 0%, #450a0a 50%, #7f1d1d 100%)",
        "surface": "rgba(255, 255, 255, 0.08)",
        "text": "#fef2f2",
        "accent": "#ef4444",
        "radius": 14,
        "blur": 16,
        "overlayOpacity": 0.15,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "fresh-spring-grad",
        "name": "Bahor Nafasi (Fresh Spring)",
        "category": "gradient",
        "tags": ["gradient", "bahor", "spring", "yashil", "fresh", "yangi", "tabiat"],
        "backgroundType": "gradient",
        "gradient": "linear-gradient(135deg, #14532d 0%, #15803d 50%, #65a30d 100%)",
        "surface": "rgba(255, 255, 255, 0.12)",
        "text": "#ffffff",
        "accent": "#bef264",
        "radius": 16,
        "blur": 16,
        "overlayOpacity": 0.15,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },

    # ==================== 3. PICTURE / TAPLINK STYLE WALLPAPERS (16) ====================
    {
        "id": "pic-3d-liquid-glass",
        "name": "3D Shaffof Suyuqlik (Liquid Glass)",
        "category": "picture",
        "tags": ["rasm", "3d", "shisha", "glass", "liquid", "suyuqlik", "abstract", "trend", "premium"],
        "backgroundType": "image",
        "backgroundImage": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80",
        "surface": "rgba(15, 23, 42, 0.72)",
        "text": "#ffffff",
        "accent": "#6366f1",
        "radius": 16,
        "blur": 14,
        "overlayOpacity": 0.25,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "pic-3d-holographic-spheres",
        "name": "3D Golografik Sharlar (Spheres)",
        "category": "picture",
        "tags": ["rasm", "3d", "sharlar", "spheres", "gologramma", "holographic", "kelajak", "zamonaviy"],
        "backgroundType": "image",
        "backgroundImage": "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=1200&q=80",
        "surface": "rgba(20, 15, 35, 0.75)",
        "text": "#ffffff",
        "accent": "#ec4899",
        "radius": 16,
        "blur": 14,
        "overlayOpacity": 0.3,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "pic-3d-neon-waves",
        "name": "3D Neon To'lqinlar (Neon Flow)",
        "category": "picture",
        "tags": ["rasm", "3d", "neon", "tolqin", "waves", "flow", "cyber", "yorqin"],
        "backgroundType": "image",
        "backgroundImage": "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=1200&q=80",
        "surface": "rgba(10, 10, 25, 0.78)",
        "text": "#ffffff",
        "accent": "#06b6d4",
        "radius": 16,
        "blur": 14,
        "overlayOpacity": 0.3,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "pic-3d-luxury-marble",
        "name": "Oltin Marmar & 3D Nurlanish",
        "category": "picture",
        "tags": ["rasm", "marmar", "marble", "oltin", "gold", "luxury", "qimmatbaho", "brend"],
        "backgroundType": "image",
        "backgroundImage": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
        "surface": "rgba(20, 16, 12, 0.8)",
        "text": "#fef3c7",
        "accent": "#f59e0b",
        "radius": 14,
        "blur": 14,
        "overlayOpacity": 0.35,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "pic-3d-minimal-architecture",
        "name": "3D Minimalist Arxitektura",
        "category": "picture",
        "tags": ["rasm", "3d", "arxitektura", "minimal", "bino", "biznes", "dizayn", "interyer"],
        "backgroundType": "image",
        "backgroundImage": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80",
        "surface": "rgba(15, 23, 42, 0.76)",
        "text": "#ffffff",
        "accent": "#38bdf8",
        "radius": 16,
        "blur": 14,
        "overlayOpacity": 0.3,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "pic-snow-mountain",
        "name": "Qorli Tog' Cho'qqisi",
        "category": "picture",
        "tags": ["rasm", "qish", "qor", "tog", "snow", "mountain", "winter", "muzlik", "sovuq"],
        "backgroundType": "image",
        "backgroundImage": "https://images.unsplash.com/photo-1517299321929-30e70bf3708b?auto=format&fit=crop&w=1200&q=80",
        "surface": "rgba(15, 23, 42, 0.72)",
        "text": "#ffffff",
        "accent": "#38bdf8",
        "radius": 16,
        "blur": 14,
        "overlayOpacity": 0.35,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "pic-summer-beach",
        "name": "Tropik Plyaj & Yoz",
        "category": "picture",
        "tags": ["rasm", "yoz", "plyaj", "beach", "summer", "dengiz", "quyosh", "sayohat", "travel"],
        "backgroundType": "image",
        "backgroundImage": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
        "surface": "rgba(15, 23, 42, 0.75)",
        "text": "#ffffff",
        "accent": "#06b6d4",
        "radius": 16,
        "blur": 14,
        "overlayOpacity": 0.3,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "pic-autumn-leaves",
        "name": "Oltin Kuz Bog'i",
        "category": "picture",
        "tags": ["rasm", "kuz", "autumn", "leaves", "barglar", "sariq", "romantika", "bog"],
        "backgroundType": "image",
        "backgroundImage": "https://images.unsplash.com/photo-1507783548227-544c3b8fc065?auto=format&fit=crop&w=1200&q=80",
        "surface": "rgba(28, 19, 14, 0.78)",
        "text": "#ffffff",
        "accent": "#f97316",
        "radius": 16,
        "blur": 14,
        "overlayOpacity": 0.3,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "pic-spring-sakura",
        "name": "Sakura & Bahor Gullari",
        "category": "picture",
        "tags": ["rasm", "bahor", "sakura", "gul", "spring", "flowers", "pushti", "gozallik"],
        "backgroundType": "image",
        "backgroundImage": "https://images.unsplash.com/photo-1522383225653-ed111181a951?auto=format&fit=crop&w=1200&q=80",
        "surface": "rgba(30, 10, 20, 0.75)",
        "text": "#ffffff",
        "accent": "#fb7185",
        "radius": 16,
        "blur": 14,
        "overlayOpacity": 0.35,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "pic-coffee-aesthetic",
        "name": "Issiq Qahva & Kafe",
        "category": "picture",
        "tags": ["rasm", "qahva", "coffee", "kafe", "kofe", "issiq", "restoran", "nonushta", "kuz"],
        "backgroundType": "image",
        "backgroundImage": "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=80",
        "surface": "rgba(24, 16, 12, 0.8)",
        "text": "#fffbeb",
        "accent": "#d97706",
        "radius": 14,
        "blur": 14,
        "overlayOpacity": 0.4,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "pic-gym-fitness",
        "name": "Sport Zali & Fitness",
        "category": "picture",
        "tags": ["rasm", "sport", "gym", "fitness", "zal", "mashq", "bodybuilding", "energiya", "trenirovka"],
        "backgroundType": "image",
        "backgroundImage": "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=80",
        "surface": "rgba(10, 10, 10, 0.8)",
        "text": "#ffffff",
        "accent": "#ef4444",
        "radius": 14,
        "blur": 14,
        "overlayOpacity": 0.45,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "pic-beauty-spa",
        "name": "Go'zallik & Spa Saloni",
        "category": "picture",
        "tags": ["rasm", "gozallik", "salon", "spa", "beauty", "parvarish", "ayollar", "kosmetika", "makiyaj"],
        "backgroundType": "image",
        "backgroundImage": "https://images.unsplash.com/photo-1560750588-73207b1ef5b8?auto=format&fit=crop&w=1200&q=80",
        "surface": "rgba(26, 18, 22, 0.78)",
        "text": "#ffffff",
        "accent": "#f43f5e",
        "radius": 16,
        "blur": 14,
        "overlayOpacity": 0.35,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "pic-city-night",
        "name": "Tungi Megapolis Chiroqlari",
        "category": "picture",
        "tags": ["rasm", "shahar", "tun", "chiroq", "city", "night", "megapolis", "biznes", "avto"],
        "backgroundType": "image",
        "backgroundImage": "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=1200&q=80",
        "surface": "rgba(10, 15, 28, 0.78)",
        "text": "#ffffff",
        "accent": "#38bdf8",
        "radius": 16,
        "blur": 14,
        "overlayOpacity": 0.35,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "pic-cyberpunk-tokyo",
        "name": "Cyberpunk Neon Tokio",
        "category": "picture",
        "tags": ["rasm", "cyberpunk", "neon", "tokio", "tokyo", "japan", "tun", "it", "gamer", "o'yin"],
        "backgroundType": "image",
        "backgroundImage": "https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=1200&q=80",
        "surface": "rgba(12, 10, 24, 0.8)",
        "text": "#ffffff",
        "accent": "#f43f5e",
        "radius": 16,
        "blur": 14,
        "overlayOpacity": 0.35,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "pic-galaxy-stars",
        "name": "Galaktika & Somon Yo'li",
        "category": "picture",
        "tags": ["rasm", "kosmos", "somon yo'li", "yulduzlar", "galaxy", "space", "stars", "koinot"],
        "backgroundType": "image",
        "backgroundImage": "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80",
        "surface": "rgba(8, 10, 22, 0.78)",
        "text": "#ffffff",
        "accent": "#a855f7",
        "radius": 16,
        "blur": 14,
        "overlayOpacity": 0.3,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "pic-restaurant-food",
        "name": "Restoran & Gourmet Taomlar",
        "category": "picture",
        "tags": ["rasm", "taom", "restoran", "oshxona", "food", "restaurant", "ovqat", "chef", "pitsa", "burger"],
        "backgroundType": "image",
        "backgroundImage": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1200&q=80",
        "surface": "rgba(20, 14, 10, 0.8)",
        "text": "#ffffff",
        "accent": "#f59e0b",
        "radius": 16,
        "blur": 14,
        "overlayOpacity": 0.4,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },

    # ==================== 4. DYNAMIC & 3D LIVE ANIMATIONS (15) ====================
    {
        "id": "anim-3d-glass-orbs",
        "name": "🔮 3D Suzuvchi Shisha Sharlar (3D Orbs)",
        "category": "animation",
        "tags": ["animatsiya", "3d", "sharlar", "orbs", "glass", "shisha", "trend", "premium", "jonli"],
        "backgroundType": "animation",
        "animationPreset": "3d-orbs",
        "background": "#0a0d18",
        "surface": "rgba(255, 255, 255, 0.1)",
        "text": "#ffffff",
        "accent": "#6366f1",
        "radius": 18,
        "blur": 18,
        "overlayOpacity": 0.15,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "anim-3d-floating-cubes",
        "name": "🧊 3D Aylanuvchi Kublar (3D Cubes)",
        "category": "animation",
        "tags": ["animatsiya", "3d", "kublar", "cubes", "geometry", "isometric", "it", "kelajak"],
        "backgroundType": "animation",
        "animationPreset": "3d-cubes",
        "background": "#090912",
        "surface": "rgba(255, 255, 255, 0.08)",
        "text": "#ffffff",
        "accent": "#38bdf8",
        "radius": 16,
        "blur": 16,
        "overlayOpacity": 0.15,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "anim-3d-cyber-horizon",
        "name": "⚡ 3D Cyber Tarmoq va Ufq (3D Grid)",
        "category": "animation",
        "tags": ["animatsiya", "3d", "cyber", "grid", "synthwave", "neon", "retro", "kelajak"],
        "backgroundType": "animation",
        "animationPreset": "3d-cyber-horizon",
        "background": "#0b001a",
        "surface": "rgba(255, 255, 255, 0.08)",
        "text": "#ffffff",
        "accent": "#ec4899",
        "radius": 16,
        "blur": 16,
        "overlayOpacity": 0.15,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "anim-3d-galaxy-warp",
        "name": "🚀 3D Fazoviy Giper-Parvoz (3D Warp)",
        "category": "animation",
        "tags": ["animatsiya", "3d", "fazo", "kosmos", "warp", "galaxy", "space", "yulduzlar"],
        "backgroundType": "animation",
        "animationPreset": "3d-galaxy-warp",
        "background": "#030712",
        "surface": "rgba(255, 255, 255, 0.08)",
        "text": "#ffffff",
        "accent": "#a855f7",
        "radius": 16,
        "blur": 16,
        "overlayOpacity": 0.15,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "anim-3d-mesh-wave",
        "name": "🌊 3D Jonli Mesh To'lqini (3D Mesh)",
        "category": "animation",
        "tags": ["animatsiya", "3d", "mesh", "wave", "gradient", "tolqin", "zamonaviy"],
        "backgroundType": "animation",
        "animationPreset": "3d-mesh",
        "background": "#080d1a",
        "surface": "rgba(255, 255, 255, 0.1)",
        "text": "#ffffff",
        "accent": "#06b6d4",
        "radius": 18,
        "blur": 18,
        "overlayOpacity": 0.15,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "anim-golden-dust",
        "name": "👑 Oltin Zarralar (Golden Dust)",
        "category": "animation",
        "tags": ["animatsiya", "oltin", "zarra", "gold", "dust", "luxury", "vip", "brend", "shimmer"],
        "backgroundType": "animation",
        "animationPreset": "golden-dust",
        "background": "#120d05",
        "surface": "rgba(245, 158, 11, 0.12)",
        "text": "#fef3c7",
        "accent": "#f59e0b",
        "radius": 14,
        "blur": 16,
        "overlayOpacity": 0.2,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "anim-fireflies",
        "name": "💡 Tungi Yonarqo'ng'izlar (Fireflies)",
        "category": "animation",
        "tags": ["animatsiya", "chiroq", "yonarqo'ng'iz", "fireflies", "tun", "sehrli", "issiq", "tungi"],
        "backgroundType": "animation",
        "animationPreset": "fireflies",
        "background": "#07150e",
        "surface": "rgba(255, 255, 255, 0.08)",
        "text": "#ecfdf5",
        "accent": "#84cc16",
        "radius": 16,
        "blur": 16,
        "overlayOpacity": 0.15,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "anim-gradient-wave",
        "name": "🌈 Tirik Gradient To'lqini (Waves)",
        "category": "animation",
        "tags": ["animatsiya", "tolqin", "gradient", "wave", "jonli", "okean", "harakat", "ranglar"],
        "backgroundType": "animation",
        "animationPreset": "gradient-wave",
        "background": "#090d16",
        "surface": "rgba(255, 255, 255, 0.12)",
        "text": "#ffffff",
        "accent": "#6366f1",
        "radius": 16,
        "blur": 16,
        "overlayOpacity": 0.15,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "anim-snow-falling",
        "name": "❄️ Mayin Qor Yog'ishi (Falling Snow)",
        "category": "animation",
        "tags": ["animatsiya", "qish", "qor", "snow", "winter", "yangi yil", "muzlik", "sovuq"],
        "backgroundType": "animation",
        "animationPreset": "snow",
        "background": "#091528",
        "surface": "rgba(255, 255, 255, 0.1)",
        "text": "#ffffff",
        "accent": "#38bdf8",
        "radius": 16,
        "blur": 16,
        "overlayOpacity": 0.2,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "anim-sakura-falling",
        "name": "🌸 To'kilayotgan Sakura Barglari",
        "category": "animation",
        "tags": ["animatsiya", "sakura", "gul", "bahor", "leaves", "pink", "yaponiya", "ayollar"],
        "backgroundType": "animation",
        "animationPreset": "sakura",
        "background": "#1f0d19",
        "surface": "rgba(255, 255, 255, 0.1)",
        "text": "#ffffff",
        "accent": "#f43f5e",
        "radius": 16,
        "blur": 16,
        "overlayOpacity": 0.15,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "anim-fire-sparks",
        "name": "🔥 Olovli Uchqunlar (Fire Sparks)",
        "category": "animation",
        "tags": ["animatsiya", "uchqun", "olov", "fire", "sparks", "sport", "energiya", "qizil"],
        "backgroundType": "animation",
        "animationPreset": "fire-sparks",
        "background": "#1a0505",
        "surface": "rgba(255, 255, 255, 0.08)",
        "text": "#fef2f2",
        "accent": "#ef4444",
        "radius": 14,
        "blur": 16,
        "overlayOpacity": 0.2,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "anim-matrix-digital",
        "name": "💻 Matrix Raqamli Yomg'ir",
        "category": "animation",
        "tags": ["animatsiya", "matrix", "kod", "dasturchi", "hacker", "yashil", "it"],
        "backgroundType": "animation",
        "animationPreset": "matrix",
        "background": "#020f06",
        "surface": "rgba(255, 255, 255, 0.07)",
        "text": "#86efac",
        "accent": "#22c55e",
        "radius": 14,
        "blur": 16,
        "overlayOpacity": 0.15,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "anim-floating-bubbles",
        "name": "🫧 Suzuvchi Pufakchalar (Bubbles)",
        "category": "animation",
        "tags": ["animatsiya", "pufakcha", "bubbles", "suv", "toza", "gozallik", "bolalar"],
        "backgroundType": "animation",
        "animationPreset": "bubbles",
        "background": "#081a2e",
        "surface": "rgba(255, 255, 255, 0.1)",
        "text": "#ffffff",
        "accent": "#0ea5e9",
        "radius": 18,
        "blur": 16,
        "overlayOpacity": 0.15,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "anim-rain-mist",
        "name": "🌧️ Romantik Yomg'ir (Rainy Mist)",
        "category": "animation",
        "tags": ["animatsiya", "yomgir", "suv", "rain", "kuz", "mist", "romantika", "chayqalish"],
        "backgroundType": "animation",
        "animationPreset": "rain",
        "background": "#0b1120",
        "surface": "rgba(255, 255, 255, 0.08)",
        "text": "#ffffff",
        "accent": "#60a5fa",
        "radius": 16,
        "blur": 16,
        "overlayOpacity": 0.2,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
    {
        "id": "anim-particles-stars",
        "name": "✨ Yulduzli Porlash (Starlight)",
        "category": "animation",
        "tags": ["animatsiya", "yulduz", "chiroq", "particles", "stars", "sehrli", "sehr"],
        "backgroundType": "animation",
        "animationPreset": "particles",
        "background": "#0a0a14",
        "surface": "rgba(255, 255, 255, 0.08)",
        "text": "#ffffff",
        "accent": "#a855f7",
        "radius": 16,
        "blur": 16,
        "overlayOpacity": 0.15,
        "overlayColor": "#000000",
        "buttonStyle": "glass",
    },
]


@router.get("")
def get_themes(
    q: Optional[str] = Query(None, description="Search term across name, category, and tags"),
    category: Optional[str] = Query(None, description="Filter by category: basic, gradient, picture, animation"),
    limit: Optional[int] = Query(None, description="Max items to return for pagination"),
    offset: int = Query(0, description="Pagination offset"),
) -> list[dict[str, Any]]:
    filtered = THEMES_CATALOG

    if category and category != "all":
        filtered = [t for t in filtered if t.get("category") == category]

    if q:
        query = q.strip().lower()
        filtered = [
            t for t in filtered
            if query in t.get("name", "").lower()
            or query in t.get("id", "").lower()
            or query in t.get("category", "").lower()
            or any(query in tag.lower() for tag in t.get("tags", []))
        ]

    if limit is not None and limit > 0:
        return filtered[offset : offset + limit]

    return filtered[offset:]
